### ISSUE TITLE
A general way to optimize try catch performance

### ISSUE THREAD

**Issue by ysmood** [winterland1989/Action.js#1]
See how to hack V8:

https://github.com/ysmood/yaku/blob/master/src/yaku.js#L346

https://github.com/ysmood/yaku/blob/master/src/yaku.js#L361

When a function use it to try catch a pure function, it will boost the outer caller's performance.

**Comment by winterland1989** [comment]
Can you explain further on this? I mean how does v8 knows that the $tryCatchFn.apply is going to be a pure function without throwing any errors?

**Comment by ysmood** [comment]
It doesn't matter if it is a pure function, I said it because if it is, the performance boost will be more measurable. See the benchmark of Yaku's benchmark folder for more infomation.

https://github.com/ysmood/yaku/blob/master/benchmark/others/try-catch.coffee

**Comment by winterland1989** [comment]
I dont understand your test, you calculate the time inside the test function and try it outside, it does't make any sense since you skip all the try catch initialization time, all benchmark below is more straight forward and more simple will show that try and catch do hit performance:

``` coffee
test = ->
    count = 0

    foo = ->
        count++

    while count < 10000000
        foo()

test2 = ->
    count = 0

    foo = ->
        count++

    try
        while count < 10000000
            foo()
    catch e
        console.log e

start = Date.now()
test()
console.log Date.now() - start

start = Date.now()
try
    test()
catch e
    console.log e
console.log Date.now() - start

start = Date.now()
test2()
console.log Date.now() - start

```

**Comment by winterland1989** [comment]
You can even move the try & catch into the loop, that will hit more perfomance, more info from this link: http://stackoverflow.com/questions/12609527/why-isnt-try-catch-used-more-often-in-javascript/12609630#12609630

**Comment by ysmood** [comment]
You need to read more about V8, I just don't have time to explain every details, you seem don't the point of my test.

**Comment by winterland1989** [comment]
After fiddling with some v8 code, i still can't understand more about this, i take it as a bug of v8, and maybe we should fire a issue on their issue tracker?
Close it for now, it's not a general way to optimize try catch, it's more like a workaround to force v8 optimize some code normally doesn't get optimized.

**Comment by ysmood** [comment]
I say it's general because it's heavily used in some famous projects. You can say it's a general workaround, that's more properly.

There're enough js engines in this world, it's right not to waste your time on how to hack one engine. I open this issue because it may help you if you want to implement error handlers for your lib and you don't want too much impact on the performance. So it's pointless to blame v8, the reality is something you have to face, not run away.

For example, if you force the user themselves to write all the try catch, most people won't use this hack, then their programs will slow down dramatically. That's why people use libs, they don't want write too much code to make their program work fast and sound, the libs do it for them silently.

However it's still all up to yourself.

**Comment by winterland1989** [comment]
Good point, add Action.safe and Action.safeRaw combinator with ca9afc681becc09b1db661ce7c53d3e5b8e1e1eb
reference: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers
