### ISSUE TITLE
Benchmark Action.js vs Yaku

### ISSUE THREAD

**Issue by ysmood** [winterland1989/Action.js#4]
I slightly altered your test. The result shows that [Yaku](https://github.com/ysmood/yaku) is almost the same fast as Action.js. Please use the latest `io.js v2.4.0` to test.

``` coffee
Action = require '../src/Action'
Promise = require 'yaku'

Promise.nextTick = (fn) -> fn()

new Action (cb) -> cb()

.next ->
    new Action (cb) ->

        start = Date.now()

        monadicAction = (acc) ->
            new Action (cb) ->
                cb acc + 1

        a = monadicAction(0)
        for i in [0..1000]
            a = a.next monadicAction

        a.go (acc) ->
            console.log 'Action.js sync use time: ', Date.now() - start
        cb()

.next ->
    new Action (cb) ->
        start = Date.now()

        mkPromise = (acc) ->
            new Promise (resolve) ->
                resolve acc + 1

        p = mkPromise(0)
        for i in [0..1000]
            p = p.then mkPromise

        p.then (acc) ->
            console.log 'yaku      sync use time: ', Date.now() - start
            cb()

.next ->
    new Action (cb) ->

        start = Date.now()

        monadicAction = (acc) ->
            new Action (cb) ->
                setTimeout(
                    -> cb acc + 1
                    0
                )

        a = monadicAction(0)
        for i in [0..1000]
            a = a.next monadicAction

        a.go (acc) ->
            console.log 'Action.js async use time: ', Date.now() - start
        cb()

.next ->
    new Action (cb) ->
        start = Date.now()

        mkPromise = (acc) ->
            new Promise (resolve) ->
                setTimeout(
                    -> resolve acc + 1
                    0
                )

        p = mkPromise(0)
        for i in [0..1000]
            p = p.then mkPromise

        p.then (acc) ->
            console.log 'yaku      async use time: ', Date.now() - start
            cb()

.go()

```
### Result

```
io.js v2.4.0
Action.js sync use time:  4
yaku      sync use time:  5
Action.js async use time:  1435
yaku      async use time:  1435
```

I don't find it faster when deal with async task benchmark. Sync resolution is rare in the real world. If 1000 rounds execution only results in 1ms difference, apparently, it won't be the bottleneck of your program.

If you want the beauty of functional programming, please do it your best, performance is not the biggest reason why people choose FP. If you keep hacking it to match Promise, you will lose the beauty of FP. I'll tell you frankly, I don't like the newly added APIs, I'd like it to keep simple and dry.

**Comment by winterland1989** [comment]
which newly added APIs do you mean? do you meaning `Action.freeze`? Actions have a different semantics, i add this function to give an Action a Promise semantics, It's useful if you want a strict behavior.

Anyway JS has a long way to turn a CPS style callback chain into a efficient loop like ghc, all this FP stuff may not make sense in a short time, maybe this year JS will get proper TCO, at that time, Action's  semantics will shine.

I'll check io.js tomorrow, nite.

**Comment by winterland1989** [comment]
iojs seems have the same performance characters on my machine, Increase monadic step from 1000 to 1000000, freeze Action.js every 1000 step will show the difference(5~6 faster). Yaku's overhead is even 2~3 times slower than bluebird. Use your own benchmark will further show Action.js consume much lower memory, this is expected because it just do simpler work.
I can't agree with you more this difference make no real diference in real world, Action.js is not a performance replacement for Promise/A+, it's just a different thing.

Any API clean up ideas?

**Comment by winterland1989** [comment]
Not interesting in API designing?
Anyway, i found the problem in your altered code:

``` coffee
        a.go (acc) ->
            console.log 'Action.js sync use time: ', Date.now() - start
        cb()
```

should be

``` coffee
        a.go (acc) ->
            console.log 'Action.js sync use time: ', Date.now() - start
            cb()
```

Now you're not firing them sequential, of course the time used are similar because v8 will interleave them.

So can you change the code and test again? you should get something like:

1002 ' should be 1002, use time: ' 1
1002 ' should be 1002, use time: ' 9
1002 ' should be 1002, use time: ' 1412
1002 ' should be 1002, use time: ' 1493

**Comment by ysmood** [comment]
I don't like the way you say it's my fault. I just copied you code: https://github.com/winterland1989/Action.js/blob/f4bb2e935d1ff728cf0dc1ff445cf33d9a34e053/test/bench.coffee#L36

I don't have any good idea about the APIs. Maybe I just feel uncomfortable of the naming, maybe they are already good enough. If I have, I'll tell you.

**Comment by ysmood** [comment]
The result:

```
1002 ' should be 1002, use time: ' 1412
1002 ' should be 1002, use time: ' 1493
```

Still doesn't impress me much.

**Comment by winterland1989** [comment]
Ok, closing issue now, performance is not a major concern anyway. and i'm working on a better naming convention.
