### ISSUE TITLE
Fantasy-Land support

### ISSUE THREAD

**Issue by markandrus** [winterland1989/Action.js#6]
Hi @winterland1989, are you familiar with the [Fantasy Land Spec](https://github.com/fantasyland/fantasy-land)? Would you consider adding methods for greater interop? Specifically
- Functor
  - `map`
- Apply
  - `ap`
- Applicative
  - `of`
- Chain
  - `chain`

**Comment by winterland1989** [comment]
I wonder shoundn't there be a `ConT` monad for Fantasy Land Spec somewhere?

The `next` method of `Action` use `instanceof` to dynamic choose a `fmap` or `>>=`, so inside a `next` you can return normal value or new `Action`, separating them will be more aligned to category theory, but complex dynamic use IMO.

I'm afraid if a js programmer find he has to write something like this:

``` js
actionA
.fmap(function(x){
    return x + 1;
})
.bind(function(x){
    return ActionB;
})
```

He'll confusion why we can't use a single function?

**Comment by markandrus** [comment]
> I wonder shoundn't there be a ConT monad for Fantasy Land Spec somewhere?

Yes, I believe there are some, but the more the merrier, IMO. :-)

`next` using `instanceof` to dynamically choose `fmap` or `>>=` is very much like `Promise.then`, and many programmers find this useful. I think you could keep the `next` method while exposing the underlying `fmap` and `>>=` methods. This would make Action.js match the Fantasy Land spec.

Fantasy Land doesn't restrict you from including additional methods—it just means you can count on those methods that come from the theory behaving consistently across libraries.

**Comment by winterland1989** [comment]
Ok, i see your point, in case of bloating library, which i'm using in browser now days, i'll write a new `ActionFL` when i got time : )

**Comment by markandrus** [comment]
:+1: :-)

**Comment by winterland1989** [comment]
Gonna close this, after adding `jsonp` and `ajax`, this library are much browser oriented now, sorry but i won't risk bloating it.
